pod 'PNChart', :git => 'https://github.com/forsythetony/PNChart.git'
pod 'SWTableViewCell'
pod 'Colours', :git => 'https://github.com/forsythetony/Colours.git'
pod 'FlatUIKit'
pod 'IQKeyboardManager', '~>2.5.0'
pod 'CRToast', '~> 0.0.4'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'FPBrandColors', '~> 0.1.3'
